# Theme
theme = "dracula"

# Editor Config
[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true


    
